project_name: pimp

env:
  - PIMP_AUTHOR=Aymeric Beaumet <hi@aymericbeaumet.com>
  - PIMP_DESCRIPTION=Command expander and task runner with pattern matching, templating and scripting capabilities
  - PIMP_HOMEPAGE=https://pimp.dev
  - PIMP_LICENSE=MIT
  - PIMP_SOURCE=https://github.com/aymericbeaumet/pimp

changelog:
  sort: asc
  filters:
    exclude:
      - '^GitBook:'
      - '^chore:'
      - '^docs:'
      - '^style:'
      - '^test:'

# build

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/pimp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip

# packaging

brews:
  - tap:
      owner: aymericbeaumet
      name: homebrew-tap
      token: "{{.Env.GORELEASER_HOMEBREW_TAP_GITHUB_TOKEN}}"
    homepage: "{{.Env.PIMP_HOMEPAGE}}"
    description: "{{.Env.PIMP_DESCRIPTION}}"
    license: "{{.Env.PIMP_LICENSE}}"
    dependencies:
      - name: fzf

dockers:
  - image_templates:
      - "aymericbeaumet/{{.ProjectName}}:latest"
      - "aymericbeaumet/{{.ProjectName}}:{{.Tag}}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.authors={{.Env.PIMP_AUTHOR}}"
      - "--label=org.opencontainers.image.url={{.Env.PIMP_HOMEPAGE}}"
      - "--label=org.opencontainers.image.source={{.Env.PIMP_SOURCE}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses={{.Env.PIMP_LICENSE}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.Env.PIMP_DESCRIPTION}}"
      - "--platform=linux/amd64"
    use_buildx: true

nfpms:
  - homepage: "{{.Env.PIMP_HOMEPAGE}}"
    maintainer: "{{.Env.PIMP_AUTHOR}}"
    description: "{{.Env.PIMP_DESCRIPTION}}"
    license: "{{.Env.PIMP_LICENSE}}"
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - fzf

# release

release:
  github:
    owner: aymericbeaumet
    name: pimp
  prerelease: auto
