name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check go.mod and go.sum are up to date
        run: |
          go mod tidy
          [ -z "$(git status --porcelain)" ] || exit 1

      - name: Build and install pimp
        run: go install .

      - name: Check the readme is up to date
        run: |
          pimp generate-readme
          [ -z "$(git status --porcelain)" ] || exit 1

      - name: Run tests
        run: go test -v ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
