name: Continuous Integration

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://github.com/golang/go/releases

      - name: Check go.mod and go.sum are up to date
        run: |
          go mod tidy
          [ -z "$(git status --porcelain)" ] || exit 1

      - name: Build and install pimp
        run: go install .

      - name: Check the readme is up to date
        run: |
          pimp generate-readme
          [ -z "$(git status --porcelain)" ] || exit 1

      - name: Run tests
        run: pimp test

      - name: Run examples
        run: pimp test-examples

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://github.com/golang/go/releases

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38.0 # https://github.com/golangci/golangci-lint/releases
          args: --timeout 10m
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true

  release:
    needs: [test, lint]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://github.com/golang/go/releases

      - uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.159.0 # https://github.com/goreleaser/goreleaser/releases
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
